name: Tests

on:
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
